name = "JSONSchemaGenerator"
uuid = "9bdf4c6d-8245-448d-a46c-e4a809cb2245"
authors = ["Helge Eichhorn <git@helgeeichhorn.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
