name = "JSONSchemaGenerator"
uuid = "9bdf4c6d-8245-448d-a46c-e4a809cb2245"
authors = ["Helge Eichhorn <git@helgeeichhorn.de> and contributors"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
OrderedCollections = "1.4"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
